# 1 reading the data

In [4]:
import pandas as pd
import numpy as np
import sqlite3
import matplotlib.pyplot as plt

In [7]:
conn=sqlite3.connect('customer_churn.db')
q="""select name from sqlite_master where type='table'"""
tables = pd.read_sql(q, conn)

In [8]:
print(tables)

              name
0      db_customer
1  db_subscription
2       db_support

In [9]:
for table_name in tables['name']:
    df=pd.read_sql(f"select * from {table_name}",conn)
    globals()[f'df_{table_name}']=df

In [14]:
display(df_db_customer.head(),df_db_subscription.head(),df_db_support.head())

,customerid,name,country,state,gender,dob,interests,pincode
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12 00:00:00,travel,None
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23 00:00:00,NaN,None
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15 00:00:00,movie,None
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30 00:00:00,NaN,None
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05 00:00:00,drama,None

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaN,NaN,13.99,627,12
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,NaN,NaN,6.99,210,34
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,NaN,NaN,22.99,1725,8
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,88

,customerid,complaint_date,escalations,csat_score,col_1,comment
0,0003-MKNFE,2024-08-28 00:00:00,N,60,None,service issue
1,0003-MKNFE,2024-08-28 00:00:00,Y,10,None,demaned refund
2,0013-EXCHZ,2024-01-20 00:00:00,Y,20,None,NaN
3,0013-MHZWF,2025-03-18 00:00:00,N,90,None,guidance to renew
4,0013-SMEOE,2024-11-01 00:00:00,N,30,None,NaN

# 2 data cleaning

In [16]:
!pip install skimpy

Defaulting to user installation because normal site-packages is not writeable
Collecting skimpy
  Downloading skimpy-0.0.21-py3-none-any.whl.metadata (33 kB)
Collecting click>=8.1.7 (from skimpy)
  Downloading click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: ipykernel>=6.29.5 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from skimpy) (7.3.0)
Requirement already satisfied: numpy>=2.0.2 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from skimpy) (2.4.6)
Collecting pandas-stubs>=2.2.2.240807 (from skimpy)
  Downloading pandas_stubs-3.0.3.260530-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: pandas>=2.2.3 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from skimpy) (3.0.3)
Collecting polars>=1.17.1 (from skimpy)
  Downloading polars-1.42.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pygments>=2.18.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from skimpy) (2.20.0)
Collecting rich>=13.9.4 (from skimpy)
  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting typeguard>=4.4.1 (from skimpy)
  Downloading typeguard-4.5.2-py3-none-any.whl.metadata (3.8 kB)
Collecting pyarrow>=18.0.0 (from skimpy)
  Downloading pyarrow-25.0.0-cp314-cp314-win_amd64.whl.metadata (3.0 kB)
Collecting pydoclint>=0.6.0 (from skimpy)
  Downloading pydoclint-0.9.1-py3-none-any.whl.metadata (10 kB)
Collecting duckdb>=1.2.2 (from skimpy)
  Downloading duckdb-1.5.4-cp314-cp314-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: colorama in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from click>=8.1.7->skimpy) (0.4.6)
Requirement already satisfied: comm>=0.1.1 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (1.8.21)
Requirement already satisfied: ipython>=7.23.1 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (9.15.0)
Requirement already satisfied: jupyter-client>=8.9.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (8.9.1)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (0.2.2)
Requirement already satisfied: nest-asyncio2>=1.7.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (1.7.2)
Requirement already satisfied: packaging>=22 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (26.2)
Requirement already satisfied: psutil>=5.7 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (7.2.2)
Requirement already satisfied: pyzmq>=25 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (6.5.7)
Requirement already satisfied: traitlets>=5.4.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipykernel>=6.29.5->skimpy) (5.15.1)
Requirement already satisfied: decorator>=5.1.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (5.3.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (0.20.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (3.0.52)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (0.6.3)
Requirement already satisfied: wcwidth in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (0.8.1)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (0.8.7)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from jupyter-client>=8.9.0->ipykernel>=6.29.5->skimpy) (2.9.0.post0)
Requirement already satisfied: typing-extensions>=4.13.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from jupyter-client>=8.9.0->ipykernel>=6.29.5->skimpy) (4.15.0)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel>=6.29.5->skimpy) (4.10.0)
Requirement already satisfied: tzdata in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from pandas>=2.2.3->skimpy) (2026.2)
Collecting polars-runtime-32==1.42.1 (from polars>=1.17.1->skimpy)
  Downloading polars_runtime_32-1.42.1-cp310-abi3-win_amd64.whl.metadata (1.5 kB)
Collecting docstring_parser_fork==0.0.16 (from pydoclint>=0.6.0->skimpy)
  Downloading docstring_parser_fork-0.0.16-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: six>=1.5 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->jupyter-client>=8.9.0->ipykernel>=6.29.5->skimpy) (1.17.0)
Collecting markdown-it-py>=2.2.0 (from rich>=13.9.4->skimpy)
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.9.4->skimpy)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: executing>=1.2.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (3.0.1)
Requirement already satisfied: pure-eval in C:\Users\kesha\AppData\Roaming\Python\Python314\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (0.2.3)
Downloading skimpy-0.0.21-py3-none-any.whl (18 kB)
Downloading click-8.4.2-py3-none-any.whl (119 kB)
Downloading duckdb-1.5.4-cp314-cp314-win_amd64.whl (13.7 MB)
   ---------------------------------------- 0.0/13.7 MB ? eta -:--:--
   ------------------------ --------------- 8.4/13.7 MB 41.2 MB/s eta 0:00:01
   ---------------------------------------- 13.7/13.7 MB 34.8 MB/s  0:00:00
Downloading pandas_stubs-3.0.3.260530-py3-none-any.whl (173 kB)
Downloading polars-1.42.1-py3-none-any.whl (837 kB)
   ---------------------------------------- 0.0/837.6 kB ? eta -:--:--
   ---------------------------------------- 837.6/837.6 kB 30.4 MB/s  0:00:00
Downloading polars_runtime_32-1.42.1-cp310-abi3-win_amd64.whl (52.7 MB)
   ---------------------------------------- 0.0/52.7 MB ? eta -:--:--
   ------- -------------------------------- 10.2/52.7 MB 51.6 MB/s eta 0:00:01
   -------------- ------------------------- 18.9/52.7 MB 46.5 MB/s eta 0:00:01
   -------------------- ------------------- 27.3/52.7 MB 45.0 MB/s eta 0:00:01
   ---------------------------- ----------- 37.0/52.7 MB 45.7 MB/s eta 0:00:01
   -------------------------------- ------- 42.2/52.7 MB 41.5 MB/s eta 0:00:01
   ----------------------------------- ---- 46.4/52.7 MB 37.5 MB/s eta 0:00:01
   -------------------------------------- - 50.3/52.7 MB 34.8 MB/s eta 0:00:01
   ---------------------------------------  52.7/52.7 MB 33.7 MB/s eta 0:00:01
   ---------------------------------------- 52.7/52.7 MB 30.5 MB/s  0:00:01
Downloading pyarrow-25.0.0-cp314-cp314-win_amd64.whl (28.6 MB)
   ---------------------------------------- 0.0/28.6 MB ? eta -:--:--
   ------ --------------------------------- 4.5/28.6 MB 22.5 MB/s eta 0:00:02
   ------------- -------------------------- 9.7/28.6 MB 23.2 MB/s eta 0:00:01
   -------------------- ------------------- 14.9/28.6 MB 24.0 MB/s eta 0:00:01
   ------------------------- -------------- 18.4/28.6 MB 22.4 MB/s eta 0:00:01
   ------------------------------ --------- 21.8/28.6 MB 21.2 MB/s eta 0:00:01
   ------------------------------------ --- 26.0/28.6 MB 20.9 MB/s eta 0:00:01
   ---------------------------------------  28.6/28.6 MB 20.9 MB/s eta 0:00:01
   ---------------------------------------- 28.6/28.6 MB 19.3 MB/s  0:00:01
Downloading pydoclint-0.9.1-py3-none-any.whl (84 kB)
Downloading docstring_parser_fork-0.0.16-py3-none-any.whl (25 kB)
Downloading rich-15.0.0-py3-none-any.whl (310 kB)
Downloading markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Downloading typeguard-4.5.2-py3-none-any.whl (36 kB)
Installing collected packages: typeguard, pyarrow, polars-runtime-32, pandas-stubs, mdurl, duckdb, docstring_parser_fork, click, pydoclint, polars, markdown-it-py, rich, skimpy

   ----------------------------------------  0/13 [typeguard]
   ----------------------------------------  0/13 [typeguard]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   --- ------------------------------------  1/13 [pyarrow]
   ------ ---------------------------------  2/13 [polars-runtime-32]
   ------ ---------------------------------  2/13 [polars-runtime-32]
   ------ ---------------------------------  2/13 [polars-runtime-32]
   ------ ---------------------------------  2/13 [polars-runtime-32]
   --------- ------------------------------  3/13 [pandas-stubs]
   --------- ------------------------------  3/13 [pandas-stubs]
   ------------ ---------------------------  4/13 [mdurl]
   --------------- ------------------------  5/13 [duckdb]
   --------------- ------------------------  5/13 [duckdb]
   --------------- ------------------------  5/13 [duckdb]
   --------------- ------------------------  5/13 [duckdb]
   --------------- ------------------------  5/13 [duckdb]
   --------------- ------------------------  5/13 [duckdb]
   ------------------ ---------------------  6/13 [docstring_parser_fork]
   ------------------ ---------------------  6/13 [docstring_parser_fork]
   --------------------- ------------------  7/13 [click]
   --------------------- ------------------  7/13 [click]
   --------------------- ------------------  7/13 [click]
   ------------------------ ---------------  8/13 [pydoclint]
   ------------------------ ---------------  8/13 [pydoclint]
   ------------------------ ---------------  8/13 [pydoclint]
   ------------------------ ---------------  8/13 [pydoclint]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   --------------------------- ------------  9/13 [polars]
   ------------------------------ --------- 10/13 [markdown-it-py]
   ------------------------------ --------- 10/13 [markdown-it-py]
   ------------------------------ --------- 10/13 [markdown-it-py]
   ------------------------------ --------- 10/13 [markdown-it-py]
   ------------------------------ --------- 10/13 [markdown-it-py]
   ------------------------------ --------- 10/13 [markdown-it-py]
   ------------------------------ --------- 10/13 [markdown-it-py]
   ------------------------------ --------- 10/13 [markdown-it-py]
   --------------------------------- ------ 11/13 [rich]
   --------------------------------- ------ 11/13 [rich]
   --------------------------------- ------ 11/13 [rich]
   --------------------------------- ------ 11/13 [rich]
   --------------------------------- ------ 11/13 [rich]
   --------------------------------- ------ 11/13 [rich]
   --------------------------------- ------ 11/13 [rich]
   --------------------------------- ------ 11/13 [rich]
   --------------------------------- ------ 11/13 [rich]
   --------------------------------- ------ 11/13 [rich]
   --------------------------------- ------ 11/13 [rich]
   --------------------------------- ------ 11/13 [rich]
   --------------------------------- ------ 11/13 [rich]
   --------------------------------- ------ 11/13 [rich]
   ------------------------------------ --- 12/13 [skimpy]
   ---------------------------------------- 13/13 [skimpy]

Successfully installed click-8.4.2 docstring_parser_fork-0.0.16 duckdb-1.5.4 markdown-it-py-4.2.0 mdurl-0.1.2 pandas-stubs-3.0.3.260530 polars-1.42.1 polars-runtime-32-1.42.1 pyarrow-25.0.0 pydoclint-0.9.1 rich-15.0.0 skimpy-0.0.21 typeguard-4.5.2

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [22]:
from skimpy import skim

skim(df_db_customer)
skim(df_db_subscription)
skim(df_db_support)

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 21     │ │ string      │ 7     │                                                          │
│ │ Number of columns │ 8      │ │ object      │ 1     │                                                          │
│ └───────────────────┴────────┘ └─────────────┴───────┘                                                          │
│                                                    All null                                                     │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓  │
│ ┃ column                                            ┃ NA                   ┃ NA %                            ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩  │
│ │                      pincode                      │                   21 │                             100 │  │
│ └───────────────────────────────────────────────────┴──────────────────────┴─────────────────────────────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━┳━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┓  │
│ ┃           ┃    ┃          ┃           ┃          ┃           ┃          ┃ chars per ┃ words    ┃ total     ┃  │
│ ┃ column    ┃ NA ┃ NA %     ┃ shortest  ┃ longest  ┃ min       ┃ max      ┃ row       ┃ per row  ┃ words     ┃  │
│ ┡━━━━━━━━━━━╇━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━┩  │
│ │ customeri │  0 │        0 │ 0002-ORFB │ 0002-ORF │ 0002-ORFB │ 0023-UYU │        10 │        1 │        21 │  │
│ │     d     │    │          │     O     │    BO    │     O     │    PN    │           │          │           │  │
│ │   name    │  0 │        0 │   mira    │ raghvend │  Madhav   │ vishakha │      5.86 │        1 │        21 │  │
│ │           │    │          │           │    ra    │           │          │           │          │           │  │
│ │  country  │  3 │ 14.28571 │   India   │  India   │   India   │  Nepal   │         5 │     0.86 │        18 │  │
│ │           │    │ 42857142 │           │          │           │          │           │          │           │  │
│ │           │    │       86 │           │          │           │          │           │          │           │  │
│ │   state   │  0 │        0 │   Delhi   │  Uttar   │   Delhi   │  Uttar   │      8.86 │      1.1 │        23 │  │
│ │           │    │          │           │ Pradesh  │           │ Pradesh  │           │          │           │  │
│ │  gender   │  0 │        0 │    Men    │  Female  │  Female   │  Women   │      4.86 │        1 │        21 │  │
│ │    dob    │  0 │        0 │ 1982-04-1 │ 1982-04- │ 1976-09-2 │ 2004-12- │        19 │        2 │        42 │  │
│ │           │    │          │     2     │    12    │     1     │    01    │           │          │           │  │
│ │           │    │          │ 00:00:00  │ 00:00:00 │ 00:00:00  │ 00:00:00 │           │          │           │  │
│ │ interests │ 17 │ 80.95238 │    job    │  travel  │   drama   │  travel  │      4.75 │     0.19 │         4 │  │
│ │           │    │ 09523809 │           │          │           │          │           │          │           │  │
│ │           │    │        5 │           │          │           │          │           │          │           │  │
│ └───────────┴────┴──────────┴───────────┴──────────┴───────────┴──────────┴───────────┴──────────┴───────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 21     │ │ string      │ 8     │                                                          │
│ │ Number of columns │ 11     │ │ int64       │ 2     │                                                          │
│ └───────────────────┴────────┘ │ float64     │ 1     │                                                          │
│                                └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━┳━━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━┓  │
│ ┃ column              ┃ NA  ┃ NA %  ┃ mean    ┃ sd     ┃ p0    ┃ p25    ┃ p50    ┃ p75    ┃ p100   ┃ hist    ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━╇━━━━━━━╇━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━┩  │
│ │   monthly_charges   │   0 │     0 │   18.85 │  17.75 │  6.99 │  12.99 │  13.99 │  20.99 │  92.99 │ ▇▂   ▁  │  │
│ │        cltv         │   0 │     0 │   823.5 │  668.9 │    42 │    240 │    640 │   1150 │   2185 │ ▇▃▃▁▂▃  │  │
│ │     churn_score     │   0 │     0 │   43.29 │  32.29 │     3 │     14 │     34 │     76 │     99 │ ▇▇▃▃▃▅  │  │
│ └─────────────────────┴─────┴───────┴─────────┴────────┴───────┴────────┴────────┴────────┴────────┴─────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━┳━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┓  │
│ ┃           ┃    ┃           ┃          ┃           ┃          ┃           ┃ chars    ┃ words per ┃ total    ┃  │
│ ┃ column    ┃ NA ┃ NA %      ┃ shortest ┃ longest   ┃ min      ┃ max       ┃ per row  ┃ row       ┃ words    ┃  │
│ ┡━━━━━━━━━━━╇━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━┩  │
│ │ customeri │  0 │         0 │ 0002-ORF │ 0002-ORFB │ 0002-ORF │ 0023-UYUP │       10 │         1 │       21 │  │
│ │     d     │    │           │    BO    │     O     │    BO    │     N     │          │           │          │  │
│ │ subscript │  0 │         0 │ 2021-03- │ 2021-03-1 │ 2019-05- │ 2023-09-1 │       10 │         1 │       21 │  │
│ │ ion_start │    │           │    15    │     5     │    10    │     4     │          │           │          │  │
│ │   _date   │    │           │          │           │          │           │          │           │          │  │
│ │ subscript │  0 │         0 │   Paid   │ Refferal  │ Organic  │ Refferal  │     6.43 │         1 │       21 │  │
│ │ ion_type  │    │           │          │           │          │           │          │           │          │  │
│ │ renewal_d │  0 │         0 │ 2025-03- │ 2025-03-1 │ 2024-01- │ 2025-12-3 │       10 │         1 │       21 │  │
│ │    ate    │    │           │    15    │     5     │    05    │     1     │          │           │          │  │
│ │ plan_type │  0 │         0 │  Basic   │ Standard  │  Basic   │ Standard  │     6.95 │         1 │       21 │  │
│ │ contract_ │  0 │         0 │  Annual  │  Monthly  │  Annual  │  Monthly  │     6.43 │         1 │       21 │  │
│ │   type    │    │           │          │           │          │           │          │           │          │  │
│ │ cancellat │ 15 │ 71.428571 │ 2024-09- │ 2024-09-1 │ 2024-02- │ 2024-11-1 │       10 │      0.29 │        6 │  │
│ │ ion_date  │    │  42857143 │    10    │     0     │    28    │     5     │          │           │          │  │
│ │ cancellat │ 15 │ 71.428571 │   Too    │ Switched  │  Forgot  │    Too    │     19.8 │      0.86 │       18 │  │
│ │ ion_reaso │    │  42857143 │ expensiv │    to     │    to    │ expensive │          │           │          │  │
│ │     n     │    │           │    e     │ competito │  cancel  │           │          │           │          │  │
│ │           │    │           │          │     r     │  trial   │           │          │           │          │  │
│ └───────────┴────┴───────────┴──────────┴───────────┴──────────┴───────────┴──────────┴───────────┴──────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 9      │ │ string      │ 4     │                                                          │
│ │ Number of columns │ 6      │ │ int64       │ 1     │                                                          │
│ └───────────────────┴────────┘ │ object      │ 1     │                                                          │
│                                └─────────────┴───────┘                                                          │
│                                                    All null                                                     │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓  │
│ ┃ column                                         ┃ NA                     ┃ NA %                             ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩  │
│ │                     col_1                      │                      9 │                              100 │  │
│ └────────────────────────────────────────────────┴────────────────────────┴──────────────────────────────────┘  │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━━━━┓  │
│ ┃ column           ┃ NA   ┃ NA %    ┃ mean     ┃ sd       ┃ p0   ┃ p25   ┃ p50   ┃ p75   ┃ p100   ┃ hist     ┃  │
│ ┡━━━━━━━━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━━━━┩  │
│ │    csat_score    │    0 │       0 │    40.56 │    31.67 │   10 │    20 │    30 │    60 │     90 │  ▇▇ ▃ ▅  │  │
│ └──────────────────┴──────┴─────────┴──────────┴──────────┴──────┴───────┴───────┴───────┴────────┴──────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━┳━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┓  │
│ ┃           ┃    ┃           ┃          ┃           ┃          ┃           ┃ chars    ┃ words per ┃ total    ┃  │
│ ┃ column    ┃ NA ┃ NA %      ┃ shortest ┃ longest   ┃ min      ┃ max       ┃ per row  ┃ row       ┃ words    ┃  │
│ ┡━━━━━━━━━━━╇━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━┩  │
│ │ customeri │  0 │         0 │ 0003-MKN │ 0003-MKNF │ 0003-MKN │ 0022-TCJC │       10 │         1 │        9 │  │
│ │     d     │    │           │    FE    │     E     │    FE    │     I     │          │           │          │  │
│ │ complaint │  0 │         0 │ 2024-08- │ 2024-08-2 │ 2024-01- │ 2025-03-1 │       19 │         2 │       18 │  │
│ │   _date   │    │           │    28    │     8     │    20    │     8     │          │           │          │  │
│ │           │    │           │ 00:00:00 │ 00:00:00  │ 00:00:00 │ 00:00:00  │          │           │          │  │
│ │ escalatio │  0 │         0 │    N     │     N     │    N     │     Y     │        1 │         1 │        9 │  │
│ │    ns     │    │           │          │           │          │           │          │           │          │  │
│ │  comment  │  5 │ 55.555555 │ service  │ guidance  │ demaned  │  service  │     14.8 │         1 │        9 │  │
│ │           │    │  55555556 │  issue   │ to renew  │  refund  │   issue   │          │           │          │  │
│ └───────────┴────┴───────────┴──────────┴───────────┴──────────┴───────────┴──────────┴───────────┴──────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

In [ ]:
#in customer 
# a. rename name
# b. drop colomns intrest and pincode
# c. change dob datatype
# d. data standardizarion gender
# e. fix missing value in country